#!/bin/sh
#
# @name Gazebo baby_k
#
# @type Tilting H coaxial octarrotor
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=leonardo_race}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=baby_k}
# PX4_GZ_MODEL_POSE=${PX4_GZ_MODEL_POSE:="-9.5 -3.5 0.5 0 0 0"}


param set-default SIM_GZ_EN 1

param set-default SENS_EN_GPSSIM 1
param set-default SENS_EN_BAROSIM 0
param set-default SENS_EN_MAGSIM 1

#custom
# param set-default SYS_CTRL_ALLOC 1 #dynamic allocation
param set-default CA_AIRFRAME 13 #Tilting Multirotor
# set MAV_TYPE 14
param set-default CA_ROTOR_COUNT 8
param set-default CA_SV_TL_COUNT 2

param set-default MC_PITCH_ON_TILT 1

# param set-default MPC_THR_HOVER 0.60
#end custm

param set-default CA_ROTOR0_PX 0.185 #M1 CCW
param set-default CA_ROTOR0_PY 0.180
param set-default CA_ROTOR0_PZ 0.0135
param set-default CA_ROTOR0_KM 0.05
param set-default CA_ROTOR1_PX 0.185 #M2 CW
param set-default CA_ROTOR1_PY -0.180
param set-default CA_ROTOR1_PZ 0.0135
param set-default CA_ROTOR1_KM -0.05
param set-default CA_ROTOR2_PX -0.185  #M3 CCW
param set-default CA_ROTOR2_PY -0.180
param set-default CA_ROTOR2_PZ 0.0135
param set-default CA_ROTOR2_KM 0.05
param set-default CA_ROTOR3_PX -0.185 #M4 CW
param set-default CA_ROTOR3_PY 0.180
param set-default CA_ROTOR3_PZ 0.0135
param set-default CA_ROTOR3_KM -0.05

param set-default CA_ROTOR4_PX 0.185 #M5 CCW
param set-default CA_ROTOR4_PY -0.180
param set-default CA_ROTOR4_PZ -0.0685
param set-default CA_ROTOR4_KM 0.05
param set-default CA_ROTOR5_PX 0.185 #M6 CW
param set-default CA_ROTOR5_PY 0.180
param set-default CA_ROTOR5_PZ -0.0685
param set-default CA_ROTOR5_KM -0.05
param set-default CA_ROTOR6_PX -0.185  #M7 CCW
param set-default CA_ROTOR6_PY 0.180
param set-default CA_ROTOR6_PZ -0.0685
param set-default CA_ROTOR6_KM 0.05
param set-default CA_ROTOR7_PX -0.185 #M8 CW
param set-default CA_ROTOR7_PY -0.180
param set-default CA_ROTOR7_PZ -0.0685
param set-default CA_ROTOR7_KM -0.05

# param set-default PWM_MAIN_FUNC1 101 #esc
# param set-default PWM_MAIN_FUNC2 102
# param set-default PWM_MAIN_FUNC3 103
# param set-default PWM_MAIN_FUNC4 104
# param set-default PWM_MAIN_FUNC5 105
# param set-default PWM_MAIN_FUNC6 106
# param set-default PWM_MAIN_FUNC7 107
# param set-default PWM_MAIN_FUNC8 108

# param set-default PWM_MAIN_FUNC9 201 #servo
# param set-default PWM_MAIN_FUNC10 202

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104
param set-default SIM_GZ_EC_FUNC5 105
param set-default SIM_GZ_EC_FUNC6 106
param set-default SIM_GZ_EC_FUNC7 107
param set-default SIM_GZ_EC_FUNC8 108

param set-default SIM_GZ_EC_MIN1 150
param set-default SIM_GZ_EC_MIN2 150
param set-default SIM_GZ_EC_MIN3 150
param set-default SIM_GZ_EC_MIN4 150
param set-default SIM_GZ_EC_MIN5 150
param set-default SIM_GZ_EC_MIN6 150
param set-default SIM_GZ_EC_MIN7 150
param set-default SIM_GZ_EC_MIN8 150

param set-default SIM_GZ_EC_MAX1 1000
param set-default SIM_GZ_EC_MAX2 1000
param set-default SIM_GZ_EC_MAX3 1000
param set-default SIM_GZ_EC_MAX4 1000
param set-default SIM_GZ_EC_MAX5 1000
param set-default SIM_GZ_EC_MAX6 1000
param set-default SIM_GZ_EC_MAX7 1000
param set-default SIM_GZ_EC_MAX8 1000

param set-default SIM_GZ_SV_FUNC1 201
param set-default SIM_GZ_SV_FUNC2 202

param set-default SIM_GZ_SV_REV 1  #reverse mask for servos





